### ISSUE TITLE
Empty parameter after deleting all parameters from a task

### ISSUE THREAD

**Issue by mvinent** [sitmun/sitmun-admin-app#157] opened 2024-03-08 13:43 UTC
**Describe the bug**
After adding and deleting parameters to a task, the response from the server returns an instance of a parameter with no content.

**To Reproduce**
1. Go to admin, tasks
2. Click on task
3. Go to parameters
4. Add parameter
5. Delete parameter
6. Go to api response
7. See error

**Expected behavior**
Task parameters' response should be the same as before adding parameters.

**Screenshots**
Response from the server before adding parameters
![image](https://github.com/sitmun/sitmun-admin-app/assets/45626106/351170a8-8535-45f8-bd5e-d4ce03d061d7)

Response after adding parameters
![image](https://github.com/sitmun/sitmun-admin-app/assets/45626106/ae36b042-1624-4f82-afa1-628a8bb1af58)

Response after deleting parameters
![image](https://github.com/sitmun/sitmun-admin-app/assets/45626106/c850b9c0-d133-4fa7-a0cb-075483ef29c6)

**Comment by fjlopez** [comment] 2024-08-08 14:22
Duplicate of https://github.com/sitmun/sitmun-backend-core/issues/172

**Closed as completed by fjlopez** 2024-08-08 14:22 UTC
Labels: bug
